### ISSUE TITLE
e paper not responding

### ISSUE THREAD

**Issue by majotito** [wyolum/BADGEr#1]
This badge was working perfectly when I took it out of storage. I went to program and ran into problems. I can add code with the Adruino IDE, and I can get the serial port to work, and I can control the red LED. However, nothing I do seems to access the epaper / EPD on the front. It seems to draw, very subtly a grey line every time, maybe, it gets powered up, but I can't see that happening. I've tried all the demo programs I could find. Some don't compile since they were made for older an Arduino IDE maybe, but what I could get to compile it seemed to run except for the epaper part.
   I realize this is 7 years old, but, I'm hoping it's just something simple I'm missing, like one register or instruction that needs to be added or something.

**Comment by osbock** [comment]
what program are you using? some of the later. updates were built to
support newer displays.

**Comment by majotito** [comment]
I used whatever I could find online. Such as:
[https://github.com/wyolum/EPD](https://github.com/wyolum/EPD)
I did make some alterations to avoid errors; should I attach my code, or is there something better to try (my first time on github).

**Comment by majotito** [comment]
This is the code I've been trying to get running, with my alterations to avoid errors.
[sketch_OHS-low-pwr-MJT.zip](https://github.com/wyolum/BADGEr/files/5767607/sketch_OHS-low-pwr-MJT.zip)

**Comment by osbock** [comment]
We don't really support that, but it looks like you are using a v2 library
(different display)
try this:
https://github.com/wyolum/EPD/tree/V1_library

**Comment by majotito** [comment]
I tried this, and got a mess of errors I'm guessing came from old IDE syntax but I have no idea. I'm sorry but googling the error isn't getting me anywhere. This is the set of errors that come up when verifying the code, as zipped here. I really appreciate the help.

[OHSLowPower.zip](https://github.com/wyolum/BADGEr/files/5770656/OHSLowPower.zip)

`sketch/EReader.cpp: In member function 'void EReader::setup(EPD_size)':
EReader.cpp:105:101: error: no matching function for call to 'EPD_Class::EPD_Class(EPD_size&, const int&, const int&, const int&, const int&, const int&, const int&)'
   EPD = new EPD_Class(size, EPD_PANEL_ON, EPD_BORDER, EPD_DISCHARGE, EPD_RESET, EPD_BUSY, EPD_EPD_CS);
                                                                                                     ^
In file included from sketch/EReader.h:18:0,
                 from sketch/EReader.cpp:15:
sketch/EPD.h:122:2: note: candidate: EPD_Class::EPD_Class()
  EPD_Class();
  ^~~~~~~~~
sketch/EPD.h:122:2: note:   candidate expects 0 arguments, 7 provided
sketch/EPD.h:44:7: note: candidate: constexpr EPD_Class::EPD_Class(const EPD_Class&)
 class EPD_Class {
       ^~~~~~~~~
sketch/EPD.h:44:7: note:   candidate expects 1 argument, 7 provided
sketch/EPD.h:44:7: note: candidate: constexpr EPD_Class::EPD_Class(EPD_Class&&)
sketch/EPD.h:44:7: note:   candidate expects 1 argument, 7 provided
/Users/MTBOOK/Documents/Arduino/OHSLowPower/OHSLowPower.ino: In function 'void draw_img(SDLib::File)':
OHSLowPower:320:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_inverse);
               ^~~~~~~~
OHSLowPower:322:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_normal);
               ^~~~~~~~
OHSLowPower:323:15: error: request for member 'end' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.end();   // power down the EPD panel
               ^~~
/Users/MTBOOK/Documents/Arduino/OHSLowPower/OHSLowPower.ino: In function 'void erase_img(SDLib::File)':
OHSLowPower:331:15: error: request for member 'begin' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.begin(); // power up the EPD panel
               ^~~~~
OHSLowPower:333:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_compensate);
               ^~~~~~~~
OHSLowPower:335:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_white);
               ^~~~~~~~
exit status 1
no matching function for call to 'EPD_Class::EPD_Class(EPD_size&, const int&, const int&, const int&, const int&, const int&, const int&)'`

**Comment by majotito** [comment]
Well that on my screen is formatted badly. I'll try this:

------------------- - -
sketch/EReader.cpp: In member function 'void EReader::setup(EPD_size)':
EReader.cpp:105:101: error: no matching function for call to 'EPD_Class::EPD_Class(EPD_size&, const int&, const int&, const int&, const int&, const int&, const int&)'
   EPD = new EPD_Class(size, EPD_PANEL_ON, EPD_BORDER, EPD_DISCHARGE, EPD_RESET, EPD_BUSY, EPD_EPD_CS);
                                                                                                     ^
In file included from sketch/EReader.h:18:0,
                 from sketch/EReader.cpp:15:
sketch/EPD.h:122:2: note: candidate: EPD_Class::EPD_Class()
  EPD_Class();
  ^~~~~~~~~
sketch/EPD.h:122:2: note:   candidate expects 0 arguments, 7 provided
sketch/EPD.h:44:7: note: candidate: constexpr EPD_Class::EPD_Class(const EPD_Class&)
 class EPD_Class {
       ^~~~~~~~~
sketch/EPD.h:44:7: note:   candidate expects 1 argument, 7 provided
sketch/EPD.h:44:7: note: candidate: constexpr EPD_Class::EPD_Class(EPD_Class&&)
sketch/EPD.h:44:7: note:   candidate expects 1 argument, 7 provided
/Users/MTBOOK/Documents/Arduino/OHSLowPower/OHSLowPower.ino: In function 'void draw_img(SDLib::File)':
OHSLowPower:320:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_inverse);
               ^~~~~~~~
OHSLowPower:322:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_normal);
               ^~~~~~~~
OHSLowPower:323:15: error: request for member 'end' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.end();   // power down the EPD panel
               ^~~
/Users/MTBOOK/Documents/Arduino/OHSLowPower/OHSLowPower.ino: In function 'void erase_img(SDLib::File)':
OHSLowPower:331:15: error: request for member 'begin' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.begin(); // power up the EPD panel
               ^~~~~
OHSLowPower:333:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_compensate);
               ^~~~~~~~
OHSLowPower:335:15: error: request for member 'frame_cb' in 'ereader.EReader::EPD', which is of pointer type 'EPD_Class*' (maybe you meant to use '->' ?)
   ereader.EPD.frame_cb(0, SD_reader, EPD_white);
               ^~~~~~~~
exit status 1
no matching function for call to 'EPD_Class::EPD_Class(EPD_size&, const int&, const int&, const int&, const int&, const int&, const int&)'
--------------- -

**Comment by majotito** [comment]
OK! I chased some bugs around (not really knowing what I was doing I'm afraid) but I got it working at least sending images to the screen. Note: I did have to alter some lines in the libraries and the main program. This package at least is functional and I'll run with what is working and see what I can do now. THANKS FOR YOUR HELP!

[OHSLowPower 2.zip](https://github.com/wyolum/BADGEr/files/5771317/OHSLowPower.2.zip)

**Comment by majotito** [comment]
For what it's worth, here's the AlaMode.ino I got working after going through it. This one does not need the other libraries; it seems most of what it needs is in-line in the code. Thanks again!!
[AlaModeEPD.ino.zip](https://github.com/wyolum/BADGEr/files/5777417/AlaModeEPD.ino.zip)
